using CmsImporter.Core.ValueObjects;

namespace CmsImporter.Core.Entities;

/// <summary>
/// A single piece of imported content. The aggregate root for the <c>content_items</c> table.
/// Identity in the source CMS is <c>(SourceSystem, ExternalId)</c>; <see cref="Id"/> is our internal Guid.
/// </summary>
public sealed class ContentItem
{
    /// <summary>Internal primary key, generated by the importer on first insert.</summary>
    public Guid Id { get; set; }

    /// <summary>Identifier of this item in the originating CMS (e.g., the WordPress post id).</summary>
    public string ExternalId { get; set; } = string.Empty;

    /// <summary>
    /// Logical name of the source CMS that produced this item — e.g., "wordpress-blog",
    /// "drupal-marketing". Together with <see cref="ExternalId"/> forms the natural key.
    /// </summary>
    public string SourceSystem { get; set; } = string.Empty;

    /// <summary>The kind of content (Page, Article, Media...).</summary>
    public ContentType Type { get; set; }

    /// <summary>Human-readable title.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>URL-friendly slug. Auto-derived from <see cref="Title"/> when the source omits it.</summary>
    public string Slug { get; set; } = string.Empty;

    /// <summary>Optional author/byline.</summary>
    public string? Author { get; set; }

    /// <summary>Original publish timestamp in the source CMS, if known.</summary>
    public DateTimeOffset? PublishedAt { get; set; }

    /// <summary>Structured body (raw text + format + optional block list). Persisted as JSONB.</summary>
    public ContentBody Body { get; set; } = ContentBody.Empty();

    /// <summary>
    /// Free-form key/value metadata (category, tags, language, ...). Persisted as JSONB,
    /// supports document-style queries via PostgreSQL's <c>@&gt;</c> operator.
    /// </summary>
    public IReadOnlyDictionary<string, string> Metadata { get; set; } =
        new Dictionary<string, string>();

    /// <summary>UTC instant at which the importer last wrote this item.</summary>
    public DateTimeOffset ImportedAt { get; set; }

    /// <summary>
    /// Optimistic-concurrency token. Incremented on every update. EF Core includes this in the
    /// <c>WHERE</c> clause of <c>UPDATE</c> statements so racing writers detect collisions and
    /// retry rather than silently losing changes.
    /// </summary>
    public uint Version { get; set; }
}
